// store context actions

const GET_PRODUCTS_START = "GET_PRODUCTS_START";
const GET_PRODUCTS_END = "GET_PRODUCTS_END";
const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
const GET_REVIEWS_START = "GET_REVIEWS_START";
const GET_REVIEWS_END = "GET_REVIEWS_END";
const GET_REVIEWS_ERROR = "GET_REVIEWS_ERROR";
const UPDATE_SORT = "UPDATE_SORT";
const SORT_PRODUCTS = "SORT PRODUCTS";
const UPDATE_FILTERS = "UPDATE_FILTERS";
const FILTER_PRODUCTS = "FILTER_PRODUCTS";
const CLEAR_FILTERS = "CLEAR_FILTERS";
const ADD_TO_BASKET = "ADD_TO_BASKET";
const TOGGLE_AMOUNT = "TOGGLE_AMOUNT";
const CALCULATE_TOTAL = "CALCULATE_TOTAL";
const REMOVE_ITEM = "REMOVE_ITEM";
const CLEAR_BASKET = "CLEAR BASKET";

// user context actions

const GET_USER_START = "GET_USER_START";
const GET_USER_END = "GET_USER_END";
const GET_USER_ERROR = "GET_USER_ERROR";
const LOGOUT_USER = "LOGOUT_USER";
const GET_USER_ORDERS_START = "GET_USER_ORDERS_START";
const GET_USER_ORDERS_END = "GET_USER_ORDERS_END";
const GET_USER_ORDERS_ERROR = "GET_USER_ORDERS_ERROR";
const STORE_SINGLE_ORDER_SECRET = "STORE_SINGLE_ORDER_SECRET";
const REMOVE_SINGLE_ORDER_SECRET = "REMOVE_SINGLE_ORDER_SECRET";
const GET_USER_REVIEWS_START = "GET_USER_REVIEWS_START";
const GET_USER_REVIEWS_END = "GET_USER_REVIEWS_END";
const GET_USER_REVIEWS_ERROR = "GET_USER_REVIEWS_ERROR";
const CREATE_USER_REVIEW_START = "CREATE_USER_REVIEW_START";
const CREATE_USER_REVIEW_PROCESS = "CREATE_USER_REVIEW_PROCESS";
const CREATE_USER_REVIEW_END = "CREATE_USER_REVIEW_END";
const CREATE_USER_REVIEW_ERROR = "CREATE_USER_REVIEW_ERROR";
const DISPLAY_MESSAGE = "DISPLAY_MESSAGE";
const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
const GO_TO_CHECKOUT = "GO_TO_CHECKOUT";

export {
  GET_PRODUCTS_START,
  GET_PRODUCTS_END,
  GET_PRODUCTS_ERROR,
  GET_REVIEWS_START,
  GET_REVIEWS_END,
  GET_REVIEWS_ERROR,
  UPDATE_SORT,
  SORT_PRODUCTS,
  UPDATE_FILTERS,
  FILTER_PRODUCTS,
  CLEAR_FILTERS,
  ADD_TO_BASKET,
  TOGGLE_AMOUNT,
  CALCULATE_TOTAL,
  REMOVE_ITEM,
  CLEAR_BASKET,
  GET_USER_START,
  GET_USER_END,
  GET_USER_ERROR,
  GET_USER_ORDERS_START,
  GET_USER_ORDERS_END,
  GET_USER_ORDERS_ERROR,
  STORE_SINGLE_ORDER_SECRET,
  REMOVE_SINGLE_ORDER_SECRET,
  GET_USER_REVIEWS_START,
  GET_USER_REVIEWS_END,
  GET_USER_REVIEWS_ERROR,
  CREATE_USER_REVIEW_START,
  CREATE_USER_REVIEW_PROCESS,
  CREATE_USER_REVIEW_END,
  CREATE_USER_REVIEW_ERROR,
  DISPLAY_MESSAGE,
  TOGGLE_SIDEBAR,
  GO_TO_CHECKOUT,
  LOGOUT_USER,
};
